
# References
* Flora, David B. "Your coefficient alpha is probably wrong, but which coefficient omega is right? A tutorial on using R to obtain better reliability estimates." Advances in Methods and Practices in Psychological Science 3.4 (2020): 484-501. https://journals.sagepub.com/doi/pdf/10.1177/2515245920951747 
* Revelle, Willian. Manuscrip. 2021. An introduction to psychometric theory with applications in R.
https://personality-project.org/r/book/Chapter7.pdf 
* Revelle, William R. "psych: Procedures for personality and psychological research." (2017). 
    * Omega Implementation in R. https://github.com/cran/psych/blob/master/R/omega.R
    * Schmid-Leiman in R. https://github.com/cran/psych/blob/master/R/schmid.R 
* Starkweather, Jon (2013). Hierarchical Factor Analysis. https://it.unt.edu/sites/default/files/hierfa_l_jds_apr2013.pdf
* Vallat, R. (2018). Pingouin: statistics in Python. Journal of Open Source Software, 3(31), 1026, https://doi.org/10.21105/joss.01026
* Wolff, Hans-Georg, and Katja Preising. "Exploring item and higher order factor structure with the Schmid-Leiman solution: Syntax codes for SPSS and SAS." Behavior Research Methods 37.1 (2005): 48-58.

# Acknowledgement
* real-statistics.com
* Factor Analyzer. Python library. https://github.com/EducationalTestingService/factor_analyzer 



In [1]:
import pandas as pd
from factor_analyzer import FactorAnalyzer
import os
import numpy as np

In [2]:
rotation='oblimin'
method='minres'

In [3]:
os.getcwd()

'/Users/rafaelvalerofernandez/Documents/repositories/factor_analyzer/notebooks'

In [4]:
df_features  = pd.DataFrame(np.matrix([[1.   , 0.483, 0.34 , 0.18 , 0.277, 0.257, -0.074, 0.212, 0.226],
        [0.483, 1.   , 0.624, 0.26 , 0.433, 0.301, -0.028, 0.362, 0.236],
        [0.34 , 0.624, 1.   , 0.24 , 0.376, 0.244, 0.233, 0.577, 0.352],
        [0.18 , 0.26 , 0.24 , 1.   , 0.534, 0.654, 0.165, 0.411, 0.306],
        [0.277, 0.433, 0.376, 0.534, 1.   , 0.609, 0.041, 0.3  , 0.239],
        [0.257, 0.301, 0.244, 0.654, 0.609, 1.   , 0.133, 0.399, 0.32 ],
        [-0.074, -0.028, 0.233, 0.165, 0.041, 0.133, 1.   , 0.346, 0.206],
        [0.212, 0.362, 0.577, 0.411, 0.3  , 0.399, 0.346, 1.   , 0.457],
        [0.226, 0.236, 0.352, 0.306, 0.239, 0.32 , 0.206, 0.457, 1.   ]]))

df_features

0      1      2      3      4      5      6      7      8
0  1.000  0.483  0.340  0.180  0.277  0.257 -0.074  0.212  0.226
1  0.483  1.000  0.624  0.260  0.433  0.301 -0.028  0.362  0.236
2  0.340  0.624  1.000  0.240  0.376  0.244  0.233  0.577  0.352
3  0.180  0.260  0.240  1.000  0.534  0.654  0.165  0.411  0.306
4  0.277  0.433  0.376  0.534  1.000  0.609  0.041  0.300  0.239
5  0.257  0.301  0.244  0.654  0.609  1.000  0.133  0.399  0.320
6 -0.074 -0.028  0.233  0.165  0.041  0.133  1.000  0.346  0.206
7  0.212  0.362  0.577  0.411  0.300  0.399  0.346  1.000  0.457
8  0.226  0.236  0.352  0.306  0.239  0.320  0.206  0.457  1.000

In [5]:
#df_features.to_csv("schmid_leiman_solution.csv",index=False)

In [6]:
fa = FactorAnalyzer(rotation=rotation,
                    method=method,
                   is_corr_matrix=True)
fa.fit(df_features)

FactorAnalyzer(is_corr_matrix=True, rotation='oblimin', rotation_kwargs={})

In [7]:
fa.loadings_

array([[ 0.1221234 ,  0.51710072, -0.06385875],
       [ 0.05912014,  0.86167702, -0.00965243],
       [-0.07628023,  0.55579955,  0.49376679],
       [ 0.74855607, -0.07036534,  0.11550148],
       [ 0.63230366,  0.26470386, -0.0773999 ],
       [ 0.87095513, -0.01819603,  0.01051326],
       [ 0.01819876, -0.25205621,  0.56757538],
       [ 0.1561189 ,  0.08505298,  0.7148967 ],
       [ 0.18787657,  0.07410765,  0.39701363]])

In [8]:
pd.DataFrame(fa.loadings_)

0         1         2
0  0.122123  0.517101 -0.063859
1  0.059120  0.861677 -0.009652
2 -0.076280  0.555800  0.493767
3  0.748556 -0.070365  0.115501
4  0.632304  0.264704 -0.077400
5  0.870955 -0.018196  0.010513
6  0.018199 -0.252056  0.567575
7  0.156119  0.085053  0.714897
8  0.187877  0.074108  0.397014

In [9]:
np.dot(fa.loadings_.T,fa.loadings_).sum(axis = 1)

array([2.19326949, 1.81502064, 1.60688186])

In [10]:
2.12/1.14,1.81/0.96,1.60688186/0.8


(1.8596491228070178, 1.8854166666666667, 2.008602325)

In [11]:
2.12/3.63686274**0.5

1.1116610919900929

In [12]:
(pd.DataFrame(fa.loadings_).T*fa.get_eigenvalues()[0]**0.5).T

0         1         2
0  0.232896  0.986140 -0.121782
1  0.067901  0.989655 -0.011086
2 -0.084792  0.617820  0.548865
3  0.646305 -0.060754  0.099724
4  0.497866  0.208424 -0.060943
5  0.606866 -0.012679  0.007325
6  0.011089 -0.153578  0.345825
7  0.088745  0.048348  0.406380
8  0.096365  0.038011  0.203635

In [13]:
fa.get_communalities()

array([0.28638522, 0.74607564, 0.55853746, 0.57862807, 0.4758668 ,
       0.75900446, 0.38600534, 0.54268441, 0.19840938])

In [14]:
fa.get_eigenvalues()

(array([3.63686274, 1.31910384, 1.2356267 , 0.74546277, 0.61997442,
        0.48550516, 0.37124956, 0.32313009, 0.26308472]),
 array([ 3.18991791,  0.87955869,  0.73699158,  0.08767277,  0.01897435,
        -0.02341487, -0.04864182, -0.13957934, -0.16988251]))

In [15]:
fa.phi_

array([[1.        , 0.35742939, 0.36867244],
       [0.35742939, 1.        , 0.35593183],
       [0.36867244, 0.35593183, 1.        ]])

In [16]:
fa.get_uniquenesses()

array([0.71361478, 0.25392436, 0.44146254, 0.42137193, 0.5241332 ,
       0.24099554, 0.61399466, 0.45731559, 0.80159062])

In [17]:
fa.get_factor_variance()

(array([1.80293685, 1.47040238, 1.25825755]),
 array([0.20032632, 0.16337804, 0.13980639]),
 array([0.20032632, 0.36370436, 0.50351075]))

In [18]:
fa.get_factor_variance()[1].sum()

0.5035107532217329

In [19]:
fa2 = FactorAnalyzer(rotation=None,
                   is_corr_matrix=True,
                   method='minres',
                   n_factors=1)
fa2.fit(fa.phi_)


FactorAnalyzer(is_corr_matrix=True, n_factors=1, rotation=None,
               rotation_kwargs={})

In [20]:
fa2.phi_

In [21]:
fa2.loadings_

array([[-0.60845908],
       [-0.58742867],
       [-0.60591484]])

In [22]:
fa2.get_eigenvalues()

(array([1.72138587, 0.64733396, 0.63128017]),
 array([ 1.08242846e+00,  2.52139285e-06, -3.28602258e-06]))

In [23]:
fa2.get_factor_variance()

(array([1.08242769]), array([0.36080923]), array([0.36080923]))

In [24]:
general_component = np.dot(fa.loadings_,fa2.loadings_)
general_component

array([[-0.33937392],
       [-0.53629742],
       [-0.57925982],
       [-0.48411518],
       [-0.49332779],
       [-0.52562183],
       [-0.2069105 ],
       [-0.57812104],
       [-0.39840462]])

In [25]:
np.dot(general_component.T,general_component)

array([[2.02811178]])

In [26]:
fa.loadings_

array([[ 0.1221234 ,  0.51710072, -0.06385875],
       [ 0.05912014,  0.86167702, -0.00965243],
       [-0.07628023,  0.55579955,  0.49376679],
       [ 0.74855607, -0.07036534,  0.11550148],
       [ 0.63230366,  0.26470386, -0.0773999 ],
       [ 0.87095513, -0.01819603,  0.01051326],
       [ 0.01819876, -0.25205621,  0.56757538],
       [ 0.1561189 ,  0.08505298,  0.7148967 ],
       [ 0.18787657,  0.07410765,  0.39701363]])

In [27]:
general_component[0]

array([-0.33937392])

In [28]:
((fa.loadings_[0]/fa.get_eigenvalues()[1][0:3])**2).sum()+general_component[0]**2

array([0.46978552])

In [29]:
fa.get_eigenvalues()[1][0:3]

array([3.18991791, 0.87955869, 0.73699158])

In [30]:
(fa.loadings_[0]**2).sum()+general_component[0]**2

array([0.40155988])

In [31]:
fa.get_communalities()

array([0.28638522, 0.74607564, 0.55853746, 0.57862807, 0.4758668 ,
       0.75900446, 0.38600534, 0.54268441, 0.19840938])

In [32]:
fa2.get_uniquenesses()

array([0.62977755, 0.65492756, 0.6328672 ])

In [33]:
fa2.get_communalities()[0]*fa.get_communalities()[0]

0.10602623872280861

# Omega
https://github.com/cran/psych/blob/master/R/omega.R

https://github.com/cran/psych/blob/master/R/schmid.R


In [34]:
Vt = df_features.sum().sum() 
Vt

31.461999999999996

In [35]:
Vitem = sum(np.diag(df_features)) 
Vitem

9.0

In [36]:
gsq = general_component.sum()**2
#gsq = fa2.loadings_.sum()**2
gsq

17.151460016585627

In [37]:
#uniq = np.dot(fa.loadings_.T,fa.loadings_).sum()
#uniq
fa.get_uniquenesses()

array([0.71361478, 0.25392436, 0.44146254, 0.42137193, 0.5241332 ,
       0.24099554, 0.61399466, 0.45731559, 0.80159062])

In [38]:
uniq =fa.get_uniquenesses().sum()
uniq

4.468403221004404

In [39]:
2.03+1.14+0.96+0.80 

4.93

In [40]:
# Explained Common Variance of the general factor =  0.41 
2.03/4.93

0.4117647058823529

In [41]:
# From now we assume that data is in wide format
n, k = df_features.shape
nvar = k
nvar

9

In [42]:
C = df_features
cronbach = (k / (k - 1)) * (1 - np.trace(C) / C.sum().sum())
cronbach

0.803183205136355

In [43]:
alpha_cronbach = ((Vt-Vitem)/Vt)*(nvar/(nvar-1))
alpha_cronbach

0.803183205136355

In [44]:
omega_hierachical= gsq/Vt
omega_hierachical

0.5451484335574861

In [45]:
omega_total=(Vt-uniq)/Vt
omega_total

0.8579745972600469

In [46]:
#omega_hierachical_asymptotic
gsq/(Vt-uniq)

0.6353899466236236

In [47]:
# h**2 y u**2

In [48]:
fa.get_uniquenesses()

array([0.71361478, 0.25392436, 0.44146254, 0.42137193, 0.5241332 ,
       0.24099554, 0.61399466, 0.45731559, 0.80159062])

In [50]:
fa.loadings_

array([[ 0.1221234 ,  0.51710072, -0.06385875],
       [ 0.05912014,  0.86167702, -0.00965243],
       [-0.07628023,  0.55579955,  0.49376679],
       [ 0.74855607, -0.07036534,  0.11550148],
       [ 0.63230366,  0.26470386, -0.0773999 ],
       [ 0.87095513, -0.01819603,  0.01051326],
       [ 0.01819876, -0.25205621,  0.56757538],
       [ 0.1561189 ,  0.08505298,  0.7148967 ],
       [ 0.18787657,  0.07410765,  0.39701363]])

In [52]:
fa.get_communalities()


array([0.28638522, 0.74607564, 0.55853746, 0.57862807, 0.4758668 ,
       0.75900446, 0.38600534, 0.54268441, 0.19840938])

In [54]:
fa.get_factor_variance()

(array([1.80293685, 1.47040238, 1.25825755]),
 array([0.20032632, 0.16337804, 0.13980639]),
 array([0.20032632, 0.36370436, 0.50351075]))

In [56]:
fa.get_eigenvalues()

(array([3.63686274, 1.31910384, 1.2356267 , 0.74546277, 0.61997442,
        0.48550516, 0.37124956, 0.32313009, 0.26308472]),
 array([ 3.18991791,  0.87955869,  0.73699158,  0.08767277,  0.01897435,
        -0.02341487, -0.04864182, -0.13957934, -0.16988251]))

In [ ]:
fa.get_factor_variance()

In [58]:
(0.099/0.078)**-1

0.7878787878787877

In [59]:
fa2.get_uniquenesses()

array([0.62977755, 0.65492756, 0.6328672 ])

In [62]:
fa.loadings_[0]*fa2.get_uniquenesses()

array([ 0.07691057,  0.33866351, -0.04041411])

In [66]:
fa2.get_uniquenesses().__len__()

3

In [74]:
fa2.loadings_

array([[-0.60845908],
       [-0.58742867],
       [-0.60591484]])

In [77]:
fa3 = np.zeros(fa.loadings_.shape)
fa3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [79]:
for i in range(0,fa2.get_uniquenesses().__len__()):
    print(i, fa.loadings_[:,i]*fa2.get_uniquenesses()[i])
    fa3[:,i] = fa.loadings_[:,i]*fa2.get_uniquenesses()[i]

0 [ 0.07691057  0.03723254 -0.04803958  0.47142381  0.39821065  0.54850799
  0.01146117  0.09832018  0.11832045]
1 [ 0.33866351  0.56433602  0.36400844 -0.0460842   0.17336185 -0.01191708
 -0.16507856  0.05570354  0.04853514]
2 [-0.04041411 -0.00610871  0.31248881  0.0730971  -0.04898386  0.0066535
  0.35919984  0.45243468  0.25125691]


In [80]:
fa3

array([[ 0.07691057,  0.33866351, -0.04041411],
       [ 0.03723254,  0.56433602, -0.00610871],
       [-0.04803958,  0.36400844,  0.31248881],
       [ 0.47142381, -0.0460842 ,  0.0730971 ],
       [ 0.39821065,  0.17336185, -0.04898386],
       [ 0.54850799, -0.01191708,  0.0066535 ],
       [ 0.01146117, -0.16507856,  0.35919984],
       [ 0.09832018,  0.05570354,  0.45243468],
       [ 0.11832045,  0.04853514,  0.25125691]])

In [91]:
(fa3[0]**2).sum()+general_component[0]**2

array([0.23741617])

In [99]:
# looks like p2
(fa2.loadings_[0]**2).sum()+(general_component[0]*fa2.get_communalities()[0])**2

array([0.38600883])

In [88]:
fa.get_communalities()[0]

0.28638522126554994

In [90]:
fa.get_uniquenesses()[0]

0.71361477873445

In [98]:
fa2.get_communalities()[0]

0.3702224516135072

In [102]:
fa.get_uniquenesses()

array([0.71361478, 0.25392436, 0.44146254, 0.42137193, 0.5241332 ,
       0.24099554, 0.61399466, 0.45731559, 0.80159062])

In [103]:
fa.get_communalities()

array([0.28638522, 0.74607564, 0.55853746, 0.57862807, 0.4758668 ,
       0.75900446, 0.38600534, 0.54268441, 0.19840938])

In [104]:
fa2.get_communalities()

array([0.37022245, 0.34507244, 0.3671328 ])